# no version needed since 2020
services:
  jekyll:
    image: bretfisher/jekyll-serve
    container_name: elephane
    working_dir: /srv
    volumes:
      - .:/srv
    ports:
      - '5747:5747'
      - '35747:35747'
    command: bundle exec jekyll s --force_polling -H 0.0.0.0 -P 5747 -l --trace --livereload-port 35747
